work

diff --git a/ocaml/Makefile b/ocaml/Makefile
--- a/ocaml/Makefile
+++ b/ocaml/Makefile
@@ -29,7 +29,7 @@ defaultentry: $(DEFAULT_BUILD_TARGET)
 
 include stdlib/StdlibModules
 
-CAMLC = $(BOOT_OCAMLC) $(BOOT_STDLIBFLAGS) -use-prims runtime4/primitives
+CAMLC = $(BOOT_OCAMLC) $(BOOT_STDLIBFLAGS) -use-prims runtime$(RUNTIME_DIR_SUFFIX)/primitives
 CAMLOPT=$(OCAMLRUN) ./ocamlopt$(EXE) $(STDLIBFLAGS) -I otherlibs/dynlink
 ARCHES=amd64 arm64 power s390x riscv
 VPATH = utils parsing typing bytecomp file_formats lambda middle_end \
@@ -603,7 +603,7 @@ expunge_MODULES = toplevel/expunge
 partialclean::
 	rm -f expunge expunge.exe
 
-# The runtime system
+# The runtime system (v4)
 
 ## Lists of source files
 
@@ -1070,6 +1070,472 @@ stdlib/libasmrun.$(A): runtime-allopt
 clean::
 	rm -f stdlib/libasmrun.a stdlib/libasmrun.lib
 
+# The runtime system (v5)
+
+## Lists of source files
+
+runtime5_COMMON_C_SOURCES = \
+  addrmap \
+  afl \
+  alloc \
+  array \
+  backtrace \
+  bigarray \
+  callback \
+  codefrag \
+  compare \
+  custom \
+  debugger \
+  domain \
+  dynlink \
+  extern \
+  fiber \
+  finalise \
+  floats \
+  gc_ctrl \
+  gc_stats \
+  globroots \
+  hash \
+  intern \
+  ints \
+  io \
+  lexing \
+  lf_skiplist \
+  main \
+  major_gc \
+  md5 \
+  memory \
+  memprof \
+  meta \
+  minor_gc \
+  misc \
+  obj \
+  parsing \
+  platform \
+  printexc \
+  prng \
+  roots \
+  runtime_events \
+  shared_heap \
+  signals \
+  skiplist \
+  startup_aux \
+  str \
+  sync \
+  sys \
+  $(UNIX_OR_WIN32) \
+  weak
+
+runtime5_BYTECODE_ONLY_C_SOURCES = \
+  backtrace_byt \
+  fail_byt \
+  fix_code \
+  interp \
+  startup_byt
+runtime5_BYTECODE_C_SOURCES = \
+  $(runtime5_COMMON_C_SOURCES:%=runtime/%.c) \
+  $(runtime5_BYTECODE_ONLY_C_SOURCES:%=runtime/%.c)
+
+runtime5_NATIVE_ONLY_C_SOURCES = \
+  backtrace_nat \
+  clambda_checks \
+  dynlink_nat \
+  fail_nat \
+  frame_descriptors \
+  startup_nat \
+  signals_nat
+runtime5_NATIVE_C_SOURCES = \
+  $(runtime5_COMMON_C_SOURCES:%=runtime/%.c) \
+  $(runtime5_NATIVE_ONLY_C_SOURCES:%=runtime/%.c)
+
+## Header files generated by configure
+runtime5_CONFIGURED_HEADERS = $(addprefix runtime/caml/, m.h s.h version.h)
+
+## Header files generated by make
+runtime5_BUILT_HEADERS = $(addprefix runtime/, \
+  caml/opnames.h caml/jumptbl.h build_config.h)
+
+## Targets to build and install
+
+runtime5_PROGRAMS = runtime/ocamlrun$(EXE)
+runtime5_BYTECODE_STATIC_LIBRARIES = $(addprefix runtime/, \
+  ld.conf libcamlrun.$(A))
+runtime5_BYTECODE_SHARED_LIBRARIES =
+runtime5_NATIVE_STATIC_LIBRARIES = runtime/libasmrun.$(A)
+runtime5_NATIVE_SHARED_LIBRARIES =
+
+ifeq "$(runtime5D)" "true"
+runtime5_PROGRAMS += runtime/ocamlrund$(EXE)
+runtime5_BYTECODE_STATIC_LIBRARIES += runtime/libcamlrund.$(A)
+runtime5_NATIVE_STATIC_LIBRARIES += runtime/libasmrund.$(A)
+endif
+
+ifeq "$(INSTRUMENTED_runtime5)" "true"
+runtime5_PROGRAMS += runtime/ocamlruni$(EXE)
+runtime5_BYTECODE_STATIC_LIBRARIES += runtime/libcamlruni.$(A)
+runtime5_NATIVE_STATIC_LIBRARIES += runtime/libasmruni.$(A)
+endif
+
+ifeq "$(UNIX_OR_WIN32)" "unix"
+ifeq "$(SUPPORTS_SHARED_LIBRARIES)" "true"
+runtime5_BYTECODE_STATIC_LIBRARIES += runtime/libcamlrun_pic.$(A)
+runtime5_BYTECODE_SHARED_LIBRARIES += runtime/libcamlrun_shared.$(SO)
+runtime5_NATIVE_STATIC_LIBRARIES += runtime/libasmrun_pic.$(A)
+runtime5_NATIVE_SHARED_LIBRARIES += runtime/libasmrun_shared.$(SO)
+endif
+endif
+
+## List of object files for each target
+
+libcamlrun_OBJECTS = $(runtime5_BYTECODE_C_SOURCES:.c=.b.$(O))
+
+libcamlrun_non_shared_OBJECTS = \
+  $(subst $(UNIX_OR_WIN32).b.$(O),$(UNIX_OR_WIN32)_non_shared.b.$(O), \
+          $(libcamlrun_OBJECTS))
+
+libcamlrund_OBJECTS = $(runtime5_BYTECODE_C_SOURCES:.c=.bd.$(O)) \
+  runtime/instrtrace.bd.$(O)
+
+libcamlruni_OBJECTS = $(runtime5_BYTECODE_C_SOURCES:.c=.bi.$(O))
+
+libcamlrunpic_OBJECTS = $(runtime5_BYTECODE_C_SOURCES:.c=.bpic.$(O))
+
+libasmrun_OBJECTS = \
+  $(runtime5_NATIVE_C_SOURCES:.c=.n.$(O)) $(runtime5_ASM_OBJECTS)
+
+libasmrund_OBJECTS = \
+  $(runtime5_NATIVE_C_SOURCES:.c=.nd.$(O)) $(runtime5_ASM_OBJECTS:.$(O)=.d.$(O))
+
+libasmruni_OBJECTS = \
+  $(runtime5_NATIVE_C_SOURCES:.c=.ni.$(O)) $(runtime5_ASM_OBJECTS:.$(O)=.i.$(O))
+
+libasmrunpic_OBJECTS = $(runtime5_NATIVE_C_SOURCES:.c=.npic.$(O)) \
+  $(runtime5_ASM_OBJECTS:.$(O)=_libasmrunpic.$(O))
+
+## General (non target-specific) assembler and compiler flags
+
+runtime5_CPPFLAGS = -DCAMLDLLIMPORT= -DIN_CAML_RUNTIME -Wno-strict-prototypes -Wno-missing-prototypes -Wno-implicit-function-declaration -DCAML_NAME_SPACE
+ocamlrund_CPPFLAGS = -DDEBUG
+ocamlruni_CPPFLAGS = -DCAML_INSTR
+
+## Runtime targets
+
+.PHONY: runtime5-all
+runtime5-all: \
+  $(runtime5_BYTECODE_STATIC_LIBRARIES) $(runtime5_BYTECODE_SHARED_LIBRARIES) \
+  $(runtime5_PROGRAMS) $(SAK)5
+
+.PHONY: runtime5-allopt
+ifeq "$(NATIVE_COMPILER)" "true"
+runtime5-allopt: \
+  $(runtime5_NATIVE_STATIC_LIBRARIES) $(runtime5_NATIVE_SHARED_LIBRARIES)
+else
+runtime5-allopt:
+	$(error The build has been configured with --disable-native-compiler)
+endif
+
+## Generated non-object files
+
+runtime/ld.conf: $(ROOTDIR)/Makefile.config
+	$(V_GEN)echo "$(STUBLIBDIR)" > $@ && \
+	echo "$(LIBDIR)" >> $@
+
+# If primitives contain duplicated lines (e.g. because the code is defined
+# like
+# #ifdef X
+# CAMLprim value caml_foo() ...
+# #else
+# CAMLprim value caml_foo() ...
+# #endif), horrible things will happen: duplicated entries in runtime5def ->
+# double registration in Symtable -> empty entry in the PRIM table ->
+# the bytecode interpreter is confused.
+# We sort the primitive file and remove duplicates to avoid this problem.
+
+# Warning: we use "sort | uniq" instead of "sort -u" because in the MSVC
+# port, the "sort" program in the path is Microsoft's and not cygwin's
+
+# Warning: POSIX sort is locale dependent, that's why we set LC_ALL explicitly.
+# Sort is unstable for "is_directory" and "isatty"
+# see http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sort.html:
+# "using sort to process pathnames, it is recommended that LC_ALL .. set to C"
+
+# To speed up builds, we avoid changing "primitives" when files
+# containing primitives change but the primitives table does not
+runtime/primitives: \
+  $(shell (cd $(ROOTDIR)/runtime && ./gen_primitives.sh) > runtime/primitives.new; \
+                    cmp -s runtime/primitives runtime/primitives.new || \
+                    echo runtime/primitives.new)
+	$(V_GEN)cp $^ $@
+
+runtime/prims.c : runtime/primitives
+	$(V_GEN)export LC_ALL=C; \
+	(echo '#include "caml/config.h"'; \
+	 echo 'typedef intnat value;'; \
+	 echo 'typedef value (*c_primitive)(void);'; \
+	 echo; \
+	 sed -e 's/.*/extern value &(void);/' $<; \
+	 echo; \
+	 echo 'const c_primitive caml_builtin_cprim[] = {'; \
+	 sed -e 's/.*/  &,/' $<; \
+	 echo '  0 };'; \
+	 echo; \
+	 echo 'const char * const caml_names_of_builtin_cprim[] = {'; \
+	 sed -e 's/.*/  "&",/' $<; \
+	 echo '  0 };') > $@
+
+runtime/caml/opnames.h : runtime/caml/instruct.h
+	$(V_GEN)tr -d '\r' < $< | \
+	sed -e '/\/\*/d' \
+	    -e '/^#/d' \
+	    -e 's/enum /static char * names_of_/' \
+	    -e 's/{$$/[] = {/' \
+	    -e 's/\([[:upper:]][[:upper:]_0-9]*\)/"\1"/g' > $@
+
+# runtime/caml/jumptbl.h is required only if you have GCC 2.0 or later
+runtime/caml/jumptbl.h : runtime/caml/instruct.h
+	$(V_GEN)tr -d '\r' < $< | \
+	sed -n -e '/^  /s/ \([A-Z]\)/ \&\&lbl_\1/gp' \
+	       -e '/^}/q' > $@
+
+# These are provided as a temporary shim to allow cross-compilation systems
+# to supply a host C compiler and different flags and a linking macro.
+SAK_CC ?= $(CC)
+SAK_CFLAGS ?= $(OC_CFLAGS) $(CFLAGS) $(OC_CPPFLAGS) $(CPPFLAGS)
+SAK_LINK ?= $(MKEXE_VIA_CC)
+
+$(SAK)5: runtime/sak.$(O)
+	$(V_MKEXE)$(call SAK_LINK,$@,$^)
+
+runtime/sak.$(O): runtime/sak.c runtime/caml/misc.h runtime/caml/config.h
+	$(V_CC)$(SAK_CC) -c $(SAK_CFLAGS) $(OUTPUTOBJ)$@ $<
+
+C_LITERAL = $(shell $(SAK)5 encode-C-literal '$(1)')
+
+runtime/build_config.h: $(ROOTDIR)/Makefile.config $(SAK)5
+	$(V_GEN)echo '/* This file is generated from $(ROOTDIR)/Makefile.config */' > $@ && \
+	echo '#define OCAML_STDLIB_DIR $(call C_LITERAL,$(LIBDIR))' >> $@ && \
+	echo '#define HOST "$(HOST)"' >> $@
+
+## Runtime libraries and programs
+
+runtime/ocamlrun$(EXE): runtime/prims.$(O) runtime/libcamlrun.$(A)
+	$(V_MKEXE)$(MKEXE) -o $@ $^ $(BYTECCLIBS)
+
+runtime/ocamlruns$(EXE): runtime/prims.$(O) runtime/libcamlrun_non_shared.$(A)
+	$(V_MKEXE)$(call MKEXE_VIA_CC,$@,$^ $(BYTECCLIBS))
+
+runtime/libcamlrun.$(A): $(libcamlrun_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/libcamlrun_non_shared.$(A): $(libcamlrun_non_shared_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/ocamlrund$(EXE): runtime/prims.$(O) runtime/libcamlrund.$(A)
+	$(V_MKEXE)$(MKEXE) $(MKEXEDEBUGFLAG) -o $@ $^ $(BYTECCLIBS)
+
+runtime/libcamlrund.$(A): $(libcamlrund_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/ocamlruni$(EXE): runtime/prims.$(O) runtime/libcamlruni.$(A)
+	$(V_MKEXE)$(MKEXE) -o $@ $^ $(INSTRUMENTED_runtime5_LIBS) $(BYTECCLIBS)
+
+runtime/libcamlruni.$(A): $(libcamlruni_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/libcamlrun_pic.$(A): $(libcamlrunpic_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/libcamlrun_shared.$(SO): $(libcamlrunpic_OBJECTS)
+	$(V_MKDLL)$(MKDLL) -o $@ $^ $(BYTECCLIBS)
+
+runtime/libasmrun.$(A): $(libasmrun_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/libasmrund.$(A): $(libasmrund_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/libasmruni.$(A): $(libasmruni_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/libasmrun_pic.$(A): $(libasmrunpic_OBJECTS)
+	$(V_MKLIB)$(call MKLIB,$@, $^)
+
+runtime/libasmrun_shared.$(SO): $(libasmrunpic_OBJECTS)
+	$(V_MKDLL)$(MKDLL) -o $@ $^ $(NATIVECCLIBS)
+
+## Runtime target-specific preprocessor and compiler flags
+
+runtime/%.$(O): OC_CPPFLAGS += $(runtime5_CPPFLAGS)
+$(DEPDIR)/runtime/%.$(D): OC_CPPFLAGS += $(runtime5_CPPFLAGS)
+
+runtime/%.bd.$(O): OC_CPPFLAGS += $(ocamlrund_CPPFLAGS)
+$(DEPDIR)/runtime/%.bd.$(D): OC_CPPFLAGS += $(ocamlrund_CPPFLAGS)
+
+runtime/%.bi.$(O): OC_CPPFLAGS += $(ocamlruni_CPPFLAGS)
+$(DEPDIR)/runtime/%.bi.$(D): OC_CPPFLAGS += $(ocamlruni_CPPFLAGS)
+
+runtime/%.bpic.$(O): OC_CFLAGS += $(SHAREDLIB_CFLAGS)
+
+runtime/%.n.$(O): OC_CFLAGS += $(OC_NATIVE_CFLAGS)
+runtime/%.n.$(O): OC_CPPFLAGS += $(OC_NATIVE_CPPFLAGS)
+$(DEPDIR)/runtime/%.n.$(D): OC_CPPFLAGS += $(OC_NATIVE_CPPFLAGS)
+
+runtime/%.nd.$(O): OC_CFLAGS += $(OC_NATIVE_CFLAGS)
+runtime/%.nd.$(O): OC_CPPFLAGS += $(OC_NATIVE_CPPFLAGS) $(ocamlrund_CPPFLAGS)
+$(DEPDIR)/runtime/%.nd.$(D): \
+  OC_CPPFLAGS += $(OC_NATIVE_CPPFLAGS) $(ocamlrund_CPPFLAGS)
+
+runtime/%.ni.$(O): OC_CFLAGS += $(OC_NATIVE_CFLAGS)
+runtime/%.ni.$(O): OC_CPPFLAGS += $(OC_NATIVE_CPPFLAGS) $(ocamlruni_CPPFLAGS)
+$(DEPDIR)/runtime/%.ni.$(D): \
+  OC_CPPFLAGS += $(OC_NATIVE_CPPFLAGS) $(ocamlruni_CPPFLAGS)
+
+runtime/%.npic.$(O): OC_CFLAGS += $(OC_NATIVE_CFLAGS) $(SHAREDLIB_CFLAGS)
+runtime/%.npic.$(O): OC_CPPFLAGS += $(OC_NATIVE_CPPFLAGS)
+$(DEPDIR)/runtime/%.npic.$(D): OC_CPPFLAGS += $(OC_NATIVE_CPPFLAGS)
+
+## Compilation of runtime C files
+
+# The COMPILE_C_FILE macro below receives as argument the pattern
+# that corresponds to the name of the generated object file
+# (without the extension, which is added by the macro)
+define COMPILE_C_FILE
+ifeq "$(COMPUTE_DEPS)" "true"
+ifneq "$(1)" "%"
+# -MG would ensure that the dependencies are generated even if the files listed
+# in $$(runtime5_BUILT_HEADERS) haven't been assembled yet. However,
+# this goes subtly wrong if the user has the headers installed,
+# as gcc will pick up a dependency on those instead and the local
+# ones will not be generated. For this reason, we don't use -MG and
+# instead include $(runtime5_BUILT_HEADERS) in the order only dependencies
+# to ensure that they exist before dependencies are computed.
+$(DEPDIR)/$(1).$(D): runtime/%.c | $(DEPDIR)/runtime $(runtime5_BUILT_HEADERS)
+	$$(V_CCDEPS)$$(DEP_CC) $$(OC_CPPFLAGS) $$(CPPFLAGS) $$< -MT \
+	  'runtime/$$*$(subst runtime/%,,$(1)).$(O)' -MF $$@
+endif # ifneq "$(1)" "%"
+$(1).$(O): $(2).c
+else
+$(1).$(O): $(2).c \
+  $(runtime5_CONFIGURED_HEADERS) $(runtime5_BUILT_HEADERS) \
+  $(runtime5_HEADERS)
+endif # ifeq "$(COMPUTE_DEPS)" "true"
+	$$(V_CC)$$(CC) -c $$(OC_CFLAGS) $$(CFLAGS) $$(OC_CPPFLAGS) $$(CPPFLAGS) \
+	  $$(OUTPUTOBJ)$$@ $$<
+endef
+
+$(DEPDIR)/runtime5:
+	$(MKDIR) $@
+
+runtime5_OBJECT_TYPES = % %.b %.bd %.bi %.bpic
+ifeq "$(NATIVE_COMPILER)" "true"
+runtime5_OBJECT_TYPES += %.n %.nd %.ni %.np %.npic
+endif
+
+$(foreach runtime5_OBJECT_TYPE, $(runtime5_OBJECT_TYPES), \
+  $(eval $(call COMPILE_C_FILE,runtime/$(runtime5_OBJECT_TYPE),runtime/%)))
+
+runtime/$(UNIX_OR_WIN32)_non_shared.%.$(O): \
+  OC_CPPFLAGS += -DBUILDING_LIBCAMLRUNS
+
+$(eval $(call COMPILE_C_FILE,runtime/$(UNIX_OR_WIN32)_non_shared.%, \
+  runtime/$(UNIX_OR_WIN32)))
+
+$(foreach runtime5_OBJECT_TYPE,$(subst %,,$(runtime5_OBJECT_TYPES)), \
+  $(eval \
+    runtime/dynlink$(runtime5_OBJECT_TYPE).$(O): $(ROOTDIR)/Makefile.config))
+
+## Compilation of runtime assembly files
+
+ASPP_ERROR = \
+  { echo "If your assembler produced syntax errors, it is probably";\
+          echo "unhappy with the preprocessor. Check your assembler, or";\
+          echo "try producing $*.o by hand.";\
+          exit 2; }
+runtime/%.o: runtime/%.S
+	$(V_ASM)$(ASPP) $(OC_ASPPFLAGS) -o $@ $< || $(ASPP_ERROR)
+
+runtime/%.d.o: runtime/%.S
+	$(V_ASM)$(ASPP) $(OC_ASPPFLAGS) $(ocamlrund_CPPFLAGS) -o $@ $< || $(ASPP_ERROR)
+
+runtime/%.i.o: runtime/%.S
+	$(V_ASM)$(ASPP) $(OC_ASPPFLAGS) $(ocamlruni_CPPFLAGS) -o $@ $< || $(ASPP_ERROR)
+
+runtime/%_libasmrunpic.o: runtime/%.S
+	$(V_ASM)$(ASPP) $(OC_ASPPFLAGS) $(SHAREDLIB_CFLAGS) -o $@ $<
+
+runtime/domain_state64.inc: \
+  runtime/gen_domain_state64_inc.awk runtime/caml/domain_state.tbl
+	$(V_GEN)$(AWK) -f $^ > $@
+
+runtime/domain_state32.inc: \
+  runtime/gen_domain_state32_inc.awk runtime/caml/domain_state.tbl
+	$(V_GEN)$(AWK) -f $^ > $@
+
+runtime/amd64nt.obj: runtime/amd64nt.asm runtime/domain_state64.inc
+	$(V_ASM)$(ASM)$@ $<
+
+runtime/amd64nt.d.obj: runtime/amd64nt.asm runtime/domain_state64.inc
+	$(V_ASM)$(ASM)$@ $(ocamlrund_CPPFLAGS) $<
+
+runtime/amd64nt.i.obj: runtime/amd64nt.asm runtime/domain_state64.inc
+	$(V_ASM)$(ASM)$@ $(ocamlruni_CPPFLAGS) $<
+
+runtime/%_libasmrunpic.obj: runtime/%.asm
+	$(V_ASM)$(ASM)$@ $<
+
+## Runtime dependencies
+
+runtime5_DEP_FILES := $(addsuffix .b, \
+  $(basename $(runtime5_BYTECODE_C_SOURCES) runtime/instrtrace))
+ifeq "$(NATIVE_COMPILER)" "true"
+runtime5_DEP_FILES += $(addsuffix .n, $(basename $(runtime5_NATIVE_C_SOURCES)))
+endif
+runtime5_DEP_FILES += $(addsuffix d, $(runtime5_DEP_FILES)) \
+             $(addsuffix i, $(runtime5_DEP_FILES)) \
+             $(addsuffix pic, $(runtime5_DEP_FILES))
+runtime5_DEP_FILES := $(addsuffix .$(D), $(runtime5_DEP_FILES))
+
+ifeq "$(COMPUTE_DEPS)" "true"
+include $(addprefix $(DEPDIR)/, $(runtime5_DEP_FILES))
+endif
+
+.PHONY: runtime5
+runtime5: stdlib/libcamlrun5.$(A)
+
+ifeq "$(BOOTSTRAPPING_FLEXDLL)" "true"
+runtime5: $(addprefix stdlib/flexdll/, $(FLEXDLL_OBJECTS))
+stdlib/flexdll/flexdll%.$(O): $(FLEXDLL_SOURCES)/flexdll%.$(O) | stdlib/flexdll
+	cp $< $@
+stdlib/flexdll:
+	$(MKDIR) $@
+endif
+
+.PHONY: makeruntime5
+makeruntime5: runtime5-all
+stdlib/libcamlrun5.$(A): runtime5-all
+	cd stdlib; $(LN) ../runtime/libcamlrun.$(A) $@
+clean::
+	rm -f $(addprefix runtime/, *.o *.obj *.a *.lib *.so *.dll ld.conf)
+	rm -f $(addprefix runtime/, ocamlrun ocamlrund ocamlruni ocamlruns sak)
+	rm -f $(addprefix runtime/, \
+	  ocamlrun.exe ocamlrund.exe ocamlruni.exe ocamlruns.exe sak.exe)
+	rm -f runtime/primitives runtime/primitives.new runtime/prims.c \
+	  $(runtime5_BUILT_HEADERS)
+	rm -f runtime/domain_state*.inc
+	rm -rf $(DEPDIR)
+	rm -f stdlib/libcamlrun5.a stdlib/libcamlrun5.lib
+
+.PHONY: runtime5opt
+runtime5opt: stdlib/libasmrun5.$(A)
+
+.PHONY: makeruntime5opt
+makeruntime5opt: runtime5-allopt
+stdlib/libasmrun5.$(A): runtime5-allopt
+	cd stdlib; $(LN) ../runtime/libasmrun.$(A) $@
+
+clean::
+	rm -f stdlib/libasmrun5.a stdlib/libasmrun5.lib
+
 # Dependencies
 
 subdirs = \
@@ -1092,6 +1558,10 @@ library: ocamlc
 .PHONY: library-cross
 library-cross:
 	$(MAKE) -C stdlib OCAMLRUN=../runtime4/ocamlrun$(EXE) all
+
+.PHONY: library-cross5
+library-cross5:
+	$(MAKE) -C stdlib OCAMLRUN=../runtime/ocamlrun$(EXE) all
 
 .PHONY: libraryopt
 libraryopt:
